# Generated by Django 6.0 on 2026-01-01 17:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pins', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pin',
            name='saved_by',
            field=models.ManyToManyField(blank=True, related_name='saved_pins', to=settings.AUTH_USER_MODEL),
        ),
    ]
