# Generated by Django 6.0 on 2026-01-02 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pins', '0007_follow_created_at_alter_follow_unique_together'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
