# Generated by Django 6.0 on 2026-01-02 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='boards/'),
        ),
    ]
